-- DOST admin: control over the built-in onboarding screens.
--
-- Generated by scripts/genOnboardingSeed.cjs — re-run that script rather
-- than hand-editing the seed rows below.
--
--   onboarding_screen_config  which built-in screens appear and in what
--                             order. Setting is_active = false removes a
--                             screen from the flow without losing its
--                             config. 'Name' is not removable because
--                             saveMyProfile requires a name.
--
--   onboarding_text           every admin-editable string on those
--                             screens. default_text is the shipped
--                             English copy; override_text is what the
--                             admin typed. A non-null override replaces
--                             the string in every language.
--
-- Scoring is carried by the i18n KEY (e.g. doshaQuiz.sleep.vata scores
-- Vata), so editing the text never breaks the psychometrics. Questions
-- cannot be added or removed from a built-in quiz for the same reason.

create table if not exists public.onboarding_screen_config (
  screen_key text primary key,
  label text not null,
  position int not null default 0,
  is_active boolean not null default true,
  is_removable boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.onboarding_text (
  i18n_key text primary key,
  screen_key text not null,
  field_label text not null,
  default_text text not null,
  override_text text,
  sort_order int not null default 0,
  updated_at timestamptz not null default now()
);

create index if not exists onboarding_text_screen_idx
  on public.onboarding_text (screen_key, sort_order);

insert into public.onboarding_screen_config (screen_key, label, position, is_active, is_removable)
values
  ('Name', 'Your name', 0, true, false),
  ('Intention', 'What brings you here', 1, true, true),
  ('Birth', 'Date & time of birth', 2, true, true),
  ('BirthPlace', 'Place of birth', 3, true, true),
  ('Dosha', 'Dosha (Ayurveda)', 4, true, true),
  ('Enneagram', 'Enneagram', 5, true, true),
  ('Numerology', 'Numerology', 6, true, true),
  ('TCM', 'Chinese medicine (5 elements)', 7, true, true),
  ('MBTI', 'Myers-Briggs type', 8, true, true),
  ('Varna', 'Varna disposition', 9, true, true)
on conflict (screen_key) do nothing;

insert into public.onboarding_text (i18n_key, screen_key, field_label, default_text, sort_order)
values
  ('onboarding.nameHeading', 'Name', 'Heading', 'What should Dost
call you?', 0),
  ('onboarding.nameSub', 'Name', 'Subheading', 'Just a first name is fine. You can change it any time.', 1),
  ('onboarding.namePlaceholder', 'Name', 'Input placeholder', 'Your name', 2),
  ('onboarding.privacyNote', 'Name', 'Privacy note', 'Everything you write stays private to your account.', 3),
  ('onboarding.intentionHeading', 'Intention', 'Heading', 'What would you like to reflect on, gently?', 4),
  ('onboarding.intentionPlaceholder', 'Intention', 'Input placeholder', 'A few words are enough', 5),
  ('onboarding.intentionHelper', 'Intention', 'Helper text', 'You can change this anytime.', 6),
  ('onboarding.birthHeading', 'Birth', 'Heading', 'When were you born?', 7),
  ('onboarding.unknownTime', 'Birth', 'Unknown-time toggle label', 'I don’t know the time', 8),
  ('onboarding.birthPlaceHeading', 'BirthPlace', 'Heading', 'Where were you born?', 9),
  ('onboarding.birthPlaceHelper', 'BirthPlace', 'Helper text', 'Optional, but it helps. You can skip any field and change this later in Settings.', 10),
  ('doshaQuiz.body_frame.prompt', 'Dosha', 'Q1 (Body frame) · prompt', 'My body frame is naturally:', 11),
  ('doshaQuiz.body_frame.vata', 'Dosha', 'Q1 · option A (scores Vata)', 'Thin and light (V)', 12),
  ('doshaQuiz.body_frame.pitta', 'Dosha', 'Q1 · option B (scores Pitta)', 'Medium and muscular (P)', 13),
  ('doshaQuiz.body_frame.kapha', 'Dosha', 'Q1 · option C (scores Kapha)', 'Broad and solid (K)', 14),
  ('doshaQuiz.stress.prompt', 'Dosha', 'Q2 (Under stress) · prompt', 'Under stress, I tend to become:', 15),
  ('doshaQuiz.stress.vata', 'Dosha', 'Q2 · option A (scores Vata)', 'Anxious and scattered (V)', 16),
  ('doshaQuiz.stress.pitta', 'Dosha', 'Q2 · option B (scores Pitta)', 'Irritable and sharp (P)', 17),
  ('doshaQuiz.stress.kapha', 'Dosha', 'Q2 · option C (scores Kapha)', 'Withdrawn and heavy (K)', 18),
  ('doshaQuiz.energy.prompt', 'Dosha', 'Q3 (Energy) · prompt', 'My energy through the day is:', 19),
  ('doshaQuiz.energy.vata', 'Dosha', 'Q3 · option A (scores Vata)', 'Comes in bursts, tires quickly (V)', 20),
  ('doshaQuiz.energy.pitta', 'Dosha', 'Q3 · option B (scores Pitta)', 'Strong and focused, then crashes (P)', 21),
  ('doshaQuiz.energy.kapha', 'Dosha', 'Q3 · option C (scores Kapha)', 'Steady but slow to start (K)', 22),
  ('doshaQuiz.sleep.prompt', 'Dosha', 'Q4 (Sleep) · prompt', 'My sleep is usually:', 23),
  ('doshaQuiz.sleep.vata', 'Dosha', 'Q4 · option A (scores Vata)', 'Light, easily disturbed (V)', 24),
  ('doshaQuiz.sleep.pitta', 'Dosha', 'Q4 · option B (scores Pitta)', 'Sound but shorter (P)', 25),
  ('doshaQuiz.sleep.kapha', 'Dosha', 'Q4 · option C (scores Kapha)', 'Deep and long (K)', 26),
  ('doshaQuiz.learning.prompt', 'Dosha', 'Q5 (Learning) · prompt', 'When learning something new, I:', 27),
  ('doshaQuiz.learning.vata', 'Dosha', 'Q5 · option A (scores Vata)', 'Grasp fast, forget fast (V)', 28),
  ('doshaQuiz.learning.pitta', 'Dosha', 'Q5 · option B (scores Pitta)', 'Grasp with sharp focus, remember well (P)', 29),
  ('doshaQuiz.learning.kapha', 'Dosha', 'Q5 · option C (scores Kapha)', 'Slow to grasp, never forget (K)', 30),
  ('enneagram.alreadyKnow', 'Enneagram', 'Link: already know my type', 'I already know my type', 31),
  ('enneagram.ifYouKnow', 'Enneagram', 'Eyebrow on self-report view', 'If you already know', 32),
  ('enneagram.whichType', 'Enneagram', 'Self-report heading', 'Which type feels most like you?', 33),
  ('enneagram.whichTypeLead', 'Enneagram', 'Self-report lead', 'Pick the one that already rings true. You can always change this later.', 34),
  ('enneagram.lensNotBox', 'Enneagram', 'Result note', 'A lens, not a box', 35),
  ('enneagram.skipForNow', 'Enneagram', 'Skip link', 'Skip this for now', 36),
  ('enneagram.questions.q1.prompt', 'Enneagram', 'Q1 · prompt', 'When something goes wrong, my first instinct is to...', 37),
  ('enneagram.questions.q1.o1', 'Enneagram', 'Q1 · option A', 'Figure out what I did wrong and fix it', 38),
  ('enneagram.questions.q1.o2', 'Enneagram', 'Q1 · option B', 'Make sure everyone else is okay first', 39),
  ('enneagram.questions.q1.o3', 'Enneagram', 'Q1 · option C', 'Find a way to still come out looking good', 40),
  ('enneagram.questions.q2.prompt', 'Enneagram', 'Q2 · prompt', 'I feel most myself when...', 41),
  ('enneagram.questions.q2.o1', 'Enneagram', 'Q2 · option A', 'I’m creating something meaningful, even if it’s messy', 42),
  ('enneagram.questions.q2.o2', 'Enneagram', 'Q2 · option B', 'I understand something deeply before acting', 43),
  ('enneagram.questions.q2.o3', 'Enneagram', 'Q2 · option C', 'I know exactly what to expect next', 44),
  ('enneagram.questions.q3.prompt', 'Enneagram', 'Q3 · prompt', 'My biggest fear is...', 45),
  ('enneagram.questions.q3.o1', 'Enneagram', 'Q3 · option A', 'Being ordinary or forgettable', 46),
  ('enneagram.questions.q3.o2', 'Enneagram', 'Q3 · option B', 'Being trapped, controlled, or missing out', 47),
  ('enneagram.questions.q3.o3', 'Enneagram', 'Q3 · option C', 'Being weak or controlled by others', 48),
  ('enneagram.questions.q4.prompt', 'Enneagram', 'Q4 · prompt', 'In conflict, I tend to...', 49),
  ('enneagram.questions.q4.o1', 'Enneagram', 'Q4 · option A', 'Avoid it and hope it resolves itself', 50),
  ('enneagram.questions.q4.o2', 'Enneagram', 'Q4 · option B', 'Confront it directly, head-on', 51),
  ('enneagram.questions.q4.o3', 'Enneagram', 'Q4 · option C', 'Worry about it long after it’s over', 52),
  ('enneagram.questions.q5.prompt', 'Enneagram', 'Q5 · prompt', 'People who know me well would say I’m...', 53),
  ('enneagram.questions.q5.o1', 'Enneagram', 'Q5 · option A', 'Principled, sometimes hard on myself', 54),
  ('enneagram.questions.q5.o2', 'Enneagram', 'Q5 · option B', 'Warm, always there for others', 55),
  ('enneagram.questions.q5.o3', 'Enneagram', 'Q5 · option C', 'Driven, always achieving something', 56),
  ('enneagram.questions.q6.prompt', 'Enneagram', 'Q6 · prompt', 'When I’m stressed, I...', 57),
  ('enneagram.questions.q6.o1', 'Enneagram', 'Q6 · option A', 'Withdraw and go quiet', 58),
  ('enneagram.questions.q6.o2', 'Enneagram', 'Q6 · option B', 'Keep myself busy so I don’t have to feel it', 59),
  ('enneagram.questions.q6.o3', 'Enneagram', 'Q6 · option C', 'Go along with whatever keeps the peace', 60),
  ('enneagram.questions.q7.prompt', 'Enneagram', 'Q7 · prompt', 'What I want most from others is...', 61),
  ('enneagram.questions.q7.o1', 'Enneagram', 'Q7 · option A', 'To be truly understood, not just liked', 62),
  ('enneagram.questions.q7.o2', 'Enneagram', 'Q7 · option B', 'To be trusted and given space to think', 63),
  ('enneagram.questions.q7.o3', 'Enneagram', 'Q7 · option C', 'To be respected, not controlled', 64),
  ('enneagram.questions.q8.prompt', 'Enneagram', 'Q8 · prompt', 'My relationship with rules and structure is...', 65),
  ('enneagram.questions.q8.o1', 'Enneagram', 'Q8 · option A', 'I hold myself to a high standard, often higher than others', 66),
  ('enneagram.questions.q8.o2', 'Enneagram', 'Q8 · option B', 'I like having options open, structure can feel confining', 67),
  ('enneagram.questions.q8.o3', 'Enneagram', 'Q8 · option C', 'I go with the flow, structure doesn’t matter much to me', 68),
  ('numerology.eyebrow', 'Numerology', 'Eyebrow', 'From your birth date', 69),
  ('numerology.lifePath', 'Numerology', 'Heading', 'Life Path', 70),
  ('numerology.lensNote', 'Numerology', 'Note under the result', 'This is just one lens — not a prediction, and not something you have to keep.', 71),
  ('numerology.skip', 'Numerology', 'Skip link', 'Skip / I’d rather not see this', 72),
  ('numerology.unreadable', 'Numerology', 'Fallback when it cannot be read', 'We could not read a life path from this birth date. You can skip this and continue.', 73),
  ('tcm.emotionHeading', 'TCM', 'Step 1 heading', 'When a feeling arrives first, which one is it usually?', 74),
  ('tcm.emotionLead', 'TCM', 'Step 1 lead', 'There is no right answer — pick the one that feels most familiar.', 75),
  ('tcm.emotion.Wood', 'TCM', 'Step 1 · option (scores Wood)', 'I tend to feel anger or frustration first', 76),
  ('tcm.emotion.Fire', 'TCM', 'Step 1 · option (scores Fire)', 'I tend to feel joy or overexcitement first', 77),
  ('tcm.emotion.Earth', 'TCM', 'Step 1 · option (scores Earth)', 'I tend to feel worry or overthinking first', 78),
  ('tcm.emotion.Metal', 'TCM', 'Step 1 · option (scores Metal)', 'I tend to feel grief or sadness first', 79),
  ('tcm.emotion.Water', 'TCM', 'Step 1 · option (scores Water)', 'I tend to feel fear or anxiety first', 80),
  ('tcm.climateHeading', 'TCM', 'Step 2 heading', 'Which climate feels most like home?', 81),
  ('tcm.climateLead', 'TCM', 'Step 2 lead', 'Think of where your body settles, not where you live right now.', 82),
  ('tcm.climate.Fire', 'TCM', 'Step 2 · option (scores Fire)', 'Warm and dry', 83),
  ('tcm.climate.Wood', 'TCM', 'Step 2 · option (scores Wood)', 'Cool and breezy', 84),
  ('tcm.climate.Earth', 'TCM', 'Step 2 · option (scores Earth)', 'Humid and mild', 85),
  ('tcm.climate.Metal', 'TCM', 'Step 2 · option (scores Metal)', 'Crisp and clear', 86),
  ('tcm.climate.Water', 'TCM', 'Step 2 · option (scores Water)', 'Cold, I run warm naturally', 87),
  ('mbti.optional', 'MBTI', 'Eyebrow', 'Optional', 88),
  ('mbti.heading', 'MBTI', 'Heading', 'Do you know your Myers-Briggs type?', 89),
  ('mbti.lead', 'MBTI', 'Lead', 'If you’ve taken this before (like INFP, ESTJ, etc.), share it here. If not, no worries — just skip.', 90),
  ('mbti.nonstandard', 'MBTI', 'Note for a non-standard type', 'That doesn’t look like a standard type — you can still save it, or skip.', 91),
  ('mbti.saveType', 'MBTI', 'Save button label', 'Save type', 92),
  ('varna.optional', 'Varna', 'Eyebrow', 'Optional', 93),
  ('varna.heading', 'Varna', 'Heading', 'What natural disposition feels most like you?', 94),
  ('varna.lead', 'Varna', 'Lead', 'A short reflection drawn from the Vedic idea of varna — four natural tendencies people live from. Not a caste, not a label. Pick what honestly fits.', 95),
  ('varna.questions.q1.prompt', 'Varna', 'Q1 · prompt', 'When something’s not right in a group, your first move tends to be…', 96),
  ('varna.questions.q1.o1', 'Varna', 'Q1 · option A (scores Brahmana)', 'Pause and reflect on what principle is at stake.', 97),
  ('varna.questions.q1.o2', 'Varna', 'Q1 · option B (scores Kshatriya)', 'Step in and set things straight.', 98),
  ('varna.questions.q1.o3', 'Varna', 'Q1 · option C (scores Vaishya)', 'Figure out what resource or arrangement will fix it.', 99),
  ('varna.questions.q1.o4', 'Varna', 'Q1 · option D (scores Shudra)', 'Help whoever is struggling in a hands-on way.', 100),
  ('varna.questions.q2.prompt', 'Varna', 'Q2 · prompt', 'What feels most like your natural comfort at work?', 101),
  ('varna.questions.q2.o1', 'Varna', 'Q2 · option A (scores Brahmana)', 'Studying, teaching, or deep thinking.', 102),
  ('varna.questions.q2.o2', 'Varna', 'Q2 · option B (scores Kshatriya)', 'Taking responsibility and making decisions.', 103),
  ('varna.questions.q2.o3', 'Varna', 'Q2 · option C (scores Vaishya)', 'Building, trading, growing something.', 104),
  ('varna.questions.q2.o4', 'Varna', 'Q2 · option D (scores Shudra)', 'Supporting a team and getting the work done well.', 105),
  ('varna.questions.q3.prompt', 'Varna', 'Q3 · prompt', 'Which quietly matters most to you?', 106),
  ('varna.questions.q3.o1', 'Varna', 'Q3 · option A (scores Brahmana)', 'Truth and inner clarity.', 107),
  ('varna.questions.q3.o2', 'Varna', 'Q3 · option B (scores Kshatriya)', 'Honour, courage, and protecting what matters.', 108),
  ('varna.questions.q3.o3', 'Varna', 'Q3 · option C (scores Vaishya)', 'Stability, prosperity, and generosity.', 109),
  ('varna.questions.q3.o4', 'Varna', 'Q3 · option D (scores Shudra)', 'Loyalty, service, and belonging.', 110),
  ('varna.questions.q4.prompt', 'Varna', 'Q4 · prompt', 'When you’re tired, you most naturally reach for…', 111),
  ('varna.questions.q4.o1', 'Varna', 'Q4 · option A (scores Brahmana)', 'Silence, scripture, or a long conversation about meaning.', 112),
  ('varna.questions.q4.o2', 'Varna', 'Q4 · option B (scores Kshatriya)', 'Movement, challenge, or taking charge of something.', 113),
  ('varna.questions.q4.o3', 'Varna', 'Q4 · option C (scores Vaishya)', 'Planning, organising, taking care of practical things.', 114),
  ('varna.questions.q4.o4', 'Varna', 'Q4 · option D (scores Shudra)', 'Being around people you love, doing simple things together.', 115),
  ('varna.labels.brahmana', 'Varna', 'Result label · brahmana', 'Teacher-reflector', 116),
  ('varna.labels.kshatriya', 'Varna', 'Result label · kshatriya', 'Leader-protector', 117),
  ('varna.labels.vaishya', 'Varna', 'Result label · vaishya', 'Builder-provider', 118),
  ('varna.labels.shudra', 'Varna', 'Result label · shudra', 'Server-helper', 119)
on conflict (i18n_key) do update
  set screen_key = excluded.screen_key,
      field_label = excluded.field_label,
      default_text = excluded.default_text,
      sort_order = excluded.sort_order;

alter table public.onboarding_screen_config enable row level security;
alter table public.onboarding_text enable row level security;

drop policy if exists "screen_config_read" on public.onboarding_screen_config;
create policy "screen_config_read"
  on public.onboarding_screen_config for select using (true);

drop policy if exists "screen_config_write" on public.onboarding_screen_config;
create policy "screen_config_write"
  on public.onboarding_screen_config for all using (true) with check (true);

drop policy if exists "onboarding_text_read" on public.onboarding_text;
create policy "onboarding_text_read"
  on public.onboarding_text for select using (true);

drop policy if exists "onboarding_text_write" on public.onboarding_text;
create policy "onboarding_text_write"
  on public.onboarding_text for all using (true) with check (true);

grant select, insert, update, delete on public.onboarding_screen_config to anon, authenticated;
grant select, insert, update, delete on public.onboarding_text to anon, authenticated;

notify pgrst, 'reload schema';
